-- ACTION_MASTER
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('SUBMIT', 'Submit', 1);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('VERIFY', 'Verify', 2);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('APPROVE', 'Approve', 3);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('RETURN', 'Return', 4);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('REJECT', 'Reject', 5);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('PAY', 'Pay', 6);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('POST', 'Post', 7);
INSERT INTO ACTION_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('REVERSE', 'Reverse', 8);

-- STAGE_MASTER
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('MEMBER_SUBMISSION', 'Member Submission', 1);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('AGENCY_SUBMISSION', 'Agency Submission', 2);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('VERIFIER_REVIEW', 'Verifier Review', 3);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('APPROVER_REVIEW', 'Approver Review', 4);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('PAYMENT_STAGE', 'Payment Stage', 5);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('POSTING_STAGE', 'Posting Stage', 6);
INSERT INTO STAGE_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('COMPLETION_STAGE', 'Completion Stage', 7);

-- CLAIM_TYPE_MASTER
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('NORMAL_CLAIM', 'Normal Claim', 'SETTLEMENT');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('PARTIAL_WITHDRAWAL', 'Partial Withdrawal', 'WITHDRAWAL');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('BENEFICIARY_SETTLEMENT', 'Beneficiary Settlement', 'SETTLEMENT');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('EXCESS_REFUND', 'Excess Refund', 'REFUND');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('WRONG_REMITTANCE', 'Wrong Remittance', 'REFUND');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('LEGAL_RECOVERY', 'Legal Recovery', 'RECOVERY');
INSERT INTO CLAIM_TYPE_MASTER (CODE, NAME, CATEGORY_CODE) VALUES ('REVERSAL', 'Reversal', 'REVERSAL');

-- CLAIM_SOURCE_MASTER
INSERT INTO CLAIM_SOURCE_MASTER (CODE, NAME) VALUES ('MEMBER_PORTAL', 'Member Portal');
INSERT INTO CLAIM_SOURCE_MASTER (CODE, NAME) VALUES ('AGENCY_PORTAL', 'Agency Portal');
INSERT INTO CLAIM_SOURCE_MASTER (CODE, NAME) VALUES ('CORE_OFFICE', 'Core Office');
INSERT INTO CLAIM_SOURCE_MASTER (CODE, NAME) VALUES ('SYSTEM_INITIATED', 'System Initiated');

-- SUBMISSION_CHANNEL_MASTER 
INSERT INTO SUBMISSION_CHANNEL_MASTER (CODE, NAME) VALUES ('ONLINE', 'Online');
INSERT INTO SUBMISSION_CHANNEL_MASTER (CODE, NAME) VALUES ('WALK_IN', 'Walk In');
INSERT INTO SUBMISSION_CHANNEL_MASTER (CODE, NAME) VALUES ('API', 'API');
INSERT INTO SUBMISSION_CHANNEL_MASTER (CODE, NAME) VALUES ('BULK_UPLOAD', 'Bulk Upload');

-- CESSATION_TYPE_MASTER
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('RETIREMENT', 'Retirement');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('RESIGNATION', 'Resignation');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('TERMINATION', 'Termination');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('DEATH', 'Death');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('CONTRACT', 'Contract');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('SUPERANNUATION', 'Superannuation');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('COMPULORY_RETIREMENT', 'Compulsory Retirement');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('EARLY_RETIREMENT', 'Early Retirement');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('MEDICAL_GROUND', 'Medical Ground');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('DESERTER', 'Deserter');
INSERT INTO CESSATION_TYPE_MASTER (CODE, NAME) VALUES ('OTHERS', 'Others');

-- TERMINATION_REASON_TYPE_MASTER
INSERT INTO TERMINATION_REASON_TYPE_MASTER (CODE, NAME) VALUES ('DISCIPLINARY_TERMINATION', 'Disciplinary Termination');
INSERT INTO TERMINATION_REASON_TYPE_MASTER (CODE, NAME) VALUES ('CONVICTED_OF_FELONY', 'Convicted Of Felony');
INSERT INTO TERMINATION_REASON_TYPE_MASTER (CODE, NAME) VALUES ('LEAVES_SERVICE', 'Leaves Service');
INSERT INTO TERMINATION_REASON_TYPE_MASTER (CODE, NAME) VALUES ('OTHER_APPROVED_REASON', 'Other Approved Reason');

-- COMPONENT_GROUP_MASTER


-- BENEFIT_TYPE_MASTER


-- ACCOUNT_TYPE_MASTER
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('PF', 'PF');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('PENSION', 'Pension');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('EC', 'Employer Contribution');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('LOAN', 'Loan');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('LAPSE_FUND', 'Lapse Fund');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('RESERVE_ACCOUNT', 'Reserve Account');
INSERT INTO ACCOUNT_TYPE_MASTER (CODE, NAME) VALUES ('UNCLAIMED_ACCOUNT', 'Unclaimed Account');

-- RESERVE_ACCOUNT_MASTER
INSERT INTO RESERVE_ACCOUNT_MASTER (RESERVE_ACCOUNT_CODE, RESERVE_ACCOUNT_NAME, ACCOUNT_TYPE_CODE, SCHEME_TYPE_CODE)
VALUES ('GEN_RESERVE_T1', 'General Reserve Tier 1', 'RESERVE_ACCOUNT', 'TIER_1');

INSERT INTO RESERVE_ACCOUNT_MASTER (RESERVE_ACCOUNT_CODE, RESERVE_ACCOUNT_NAME, ACCOUNT_TYPE_CODE, SCHEME_TYPE_CODE)
VALUES ('GEN_RESERVE_T2', 'General Reserve Tier 2', 'RESERVE_ACCOUNT', 'TIER_2');


-- RULE MASTER 
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('HOUSING', 'Housing');
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('MEDICAL', 'Medical');
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('UNEMPLOYMENT', 'Unemployment');
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('DISABILITY', 'Disability');
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('NATURAL_DISASTER', 'Natural Disaster');
INSERT INTO PARTIAL_WITHDRAWAL_REASON_MASTER (CODE, NAME) VALUES ('BUSINESS_INVESTMENT', 'Business Investment');

-- SPECIAL CLAIM_SOURCE_MASTER
INSERT INTO SPECIAL_CASE_REFUND_AUTHORITY_MASTER (CODE, NAME) VALUES ('KASHO', 'Kasho');
INSERT INTO SPECIAL_CASE_REFUND_AUTHORITY_MASTER (CODE, NAME) VALUES ('ROYAL_EDICT', 'Royal Edict');
INSERT INTO SPECIAL_CASE_REFUND_AUTHORITY_MASTER (CODE, NAME) VALUES ('COMPETENT_AUTHORITY', 'Competent Authority');
INSERT INTO SPECIAL_CASE_REFUND_AUTHORITY_MASTER (CODE, NAME) VALUES ('OTHER_AUTHORITY', 'Other Authority');

INSERT INTO SPECIAL_CASE_REFUND_REASON_MASTER (CODE, NAME) VALUES ('CID_ISSUE', 'CID Issue');
INSERT INTO SPECIAL_CASE_REFUND_REASON_MASTER (CODE, NAME) VALUES ('KASHO', 'Kasho');
INSERT INTO SPECIAL_CASE_REFUND_REASON_MASTER (CODE, NAME) VALUES ('COMPETENT_AUTHORITY_APPROVAL', 'Competent Authority Approval');
INSERT INTO SPECIAL_CASE_REFUND_REASON_MASTER (CODE, NAME) VALUES ('OTHER', 'Other');

-- UNCLAIMED MASTER 
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('MEMBER_UNCLAIMED', 'Member Unclaimed');
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('NOMINEE_UNCLAIMED', 'Nominee Unclaimed');
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('BENEFIT_UNCLAIMED', 'Benefit Unclaimed');
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('REFUND_UNCLAIMED', 'Refund Unclaimed');
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('DEATH_SETTLEMENT_UNCLAIMED', 'Death Settlement Unclaimed');
INSERT INTO UNCLAIMED_TYPE_MASTER (CODE, NAME) VALUES ('EXIT_BENEFIT_UNCLAIMED', 'Exit Benefit Unclaimed');

INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('OPEN', 'Open', 1);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('UNDER_REVIEW', 'Under Review', 2);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('NOTICE_SENT', 'Notice Sent', 3);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('INTEREST_FREEZE_PENDING', 'Interest Freeze Pending', 4);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('INTEREST_FROZEN', 'Interest Frozen', 5);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('FORFEITURE_PENDING', 'Forfeiture Pending', 6);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('EXEMPTED', 'Exempted', 7);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('RESTORED', 'Restored', 8);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('CLOSED', 'Closed', 9);
INSERT INTO UNCLAIMED_STATUS_MASTER (CODE, NAME, DISPLAY_ORDER) VALUES ('HOLD_CASE', 'Hold Case', 10);

INSERT INTO UNCLAIMED_NOTICE_TYPE_MASTER (CODE, NAME) VALUES ('SMS', 'SMS');
INSERT INTO UNCLAIMED_NOTICE_TYPE_MASTER (CODE, NAME) VALUES ('EMAIL', 'Email');
INSERT INTO UNCLAIMED_NOTICE_TYPE_MASTER (CODE, NAME) VALUES ('LETTER', 'Letter');
INSERT INTO UNCLAIMED_NOTICE_TYPE_MASTER (CODE, NAME) VALUES ('PUBLIC_NOTICE', 'Public Notice');

INSERT INTO UNCLAIMED_PERIOD_RULE_MASTER (RULE_NAME, PERIOD_VALUE, PERIOD_UNIT)
VALUES ('UNCLAIMED_3_YEAR_RULE', 3, 'YEARS');

INSERT INTO UNCLAIMED_INTEREST_FREEZE_RULE_MASTER (CODE, NAME) VALUES ('IMMEDIATE', 'Immediate');
INSERT INTO UNCLAIMED_INTEREST_FREEZE_RULE_MASTER (CODE, NAME) VALUES ('AFTER_THRESHOLD', 'After Threshold');

INSERT INTO UNCLAIMED_FORFEITURE_RULE_MASTER (CODE, NAME) VALUES ('AFTER_THRESHOLD', 'After Threshold');
INSERT INTO UNCLAIMED_FORFEITURE_RULE_MASTER (CODE, NAME) VALUES ('MANUAL_APPROVAL_REQUIRED', 'Manual Approval Required');
INSERT INTO UNCLAIMED_FORFEITURE_RULE_MASTER (CODE, NAME) VALUES ('DISABLED', 'Disabled');

INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('NOT_REVIEWED', 'Not Reviewed');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('ACCEPTED', 'Accepted');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('MISMATCH', 'Mismatch');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('INCOMPLETE', 'Incomplete');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('INVALID', 'Invalid');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('REQUIRES_CORRECTION', 'Requires Correction');
INSERT INTO REVIEW_STATUS_MASTER (CODE, NAME) VALUES ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required');

-- Deduction Type Master
INSERT INTO DEDUCTION_TYPE_MASTER (CODE, NAME) VALUES ('LOAN_RECOVERY', 'Loan Recovery');
INSERT INTO DEDUCTION_TYPE_MASTER (CODE, NAME) VALUES ('RENTAL_RECOVERY', 'Rental Recovery');
INSERT INTO DEDUCTION_TYPE_MASTER (CODE, NAME) VALUES ('OTHER_RECOVERY', 'Other Recovery');
INSERT INTO DEDUCTION_TYPE_MASTER (CODE, NAME) VALUES ('TAX', 'Tax');
INSERT INTO DEDUCTION_TYPE_MASTER (CODE, NAME) VALUES ('PENALTY', 'Penalty');

INSERT INTO PAYMENT_MODE_MASTER (CODE, NAME) VALUES ('BANK_TRANSFER', 'Bank Transfer');
INSERT INTO PAYMENT_MODE_MASTER (CODE, NAME) VALUES ('CHEQUE', 'Cheque');
INSERT INTO PAYMENT_MODE_MASTER (CODE, NAME) VALUES ('CASH', 'Cash');

INSERT INTO PAYMENT_STATUS_MASTER (CODE, NAME) VALUES ('INITIATED', 'Initiated');
INSERT INTO PAYMENT_STATUS_MASTER (CODE, NAME) VALUES ('PROCESSING', 'Processing');
INSERT INTO PAYMENT_STATUS_MASTER (CODE, NAME) VALUES ('SUCCESS', 'Success');
INSERT INTO PAYMENT_STATUS_MASTER (CODE, NAME) VALUES ('FAILED', 'Failed');
INSERT INTO PAYMENT_STATUS_MASTER (CODE, NAME) VALUES ('REVERSED', 'Reversed');

-- LOAN SECTION
INSERT INTO LOAN_ADJUSTMENT_PRIORITY_MASTER (CODE, NAME, IS_APPLICABLE, PRIORITY_SEQUENCE)
VALUES ('MEMBER_LOAN', 'Member Loan', 'Y', 1);

INSERT INTO LOAN_ADJUSTMENT_PRIORITY_MASTER (CODE, NAME, IS_APPLICABLE, PRIORITY_SEQUENCE)
VALUES ('EDUCATION_LOAN', 'Education Loan', 'Y', 2);

INSERT INTO LOAN_ADJUSTMENT_PRIORITY_MASTER (CODE, NAME, IS_APPLICABLE, PRIORITY_SEQUENCE)
VALUES ('HOUSING_LOAN', 'Housing Loan', 'Y', 3);

INSERT INTO LOAN_ADJUSTMENT_PRIORITY_MASTER (CODE, NAME, IS_APPLICABLE, PRIORITY_SEQUENCE)
VALUES ('COMMERCIAL_HOUSING_LOAN', 'Commercial Housing Loan', 'Y', 4);

INSERT INTO LOAN_ADJUSTMENT_PRIORITY_MASTER (CODE, NAME, IS_APPLICABLE, PRIORITY_SEQUENCE)
VALUES ('RENTAL_LOAN', 'Rental Loan', 'Y', 5);

-- Refund Type Master
INSERT INTO REFUND_TYPE_MASTER (CODE, NAME) VALUES ('LUMPSUM', 'Lumpsum');
INSERT INTO REFUND_TYPE_MASTER (CODE, NAME) VALUES ('PENSION_OPTION', 'Pension Option');
INSERT INTO REFUND_TYPE_MASTER (CODE, NAME) VALUES ('PF', 'PF');
INSERT INTO REFUND_TYPE_MASTER (CODE, NAME) VALUES ('PENSION', 'Pension');
INSERT INTO REFUND_TYPE_MASTER (CODE, NAME) VALUES ('LAPSED_RESTORE', 'Lapsed Restore');

INSERT INTO REFUND_SCOPE_MASTER (CODE, NAME) VALUES ('AGENCY', 'Agency');
INSERT INTO REFUND_SCOPE_MASTER (CODE, NAME) VALUES ('MEMBER', 'Member');

INSERT INTO REFUND_SCOPE_MASTER (CODE, NAME) VALUES ('AGENCY', 'Agency');
INSERT INTO REFUND_SCOPE_MASTER (CODE, NAME) VALUES ('MEMBER', 'Member');

INSERT INTO LEGAL_RECOVERY_MASTER (CODE, NAME) VALUES ('PARTIAL_RECOVERY', 'Partial Recovery');
INSERT INTO LEGAL_RECOVERY_MASTER (CODE, NAME) VALUES ('FULL_RECOVERY', 'Full Recovery');

-- 1. Termination Before June 2013 > 12 months (Simultaneous)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, EFFECTIVE_FROM, EFFECTIVE_TO, CREATED_BY)
VALUES
('TERM_BEFORE_2013_GT_12',
 'Termination Before June 2013 More Than 1 Year',
 'TERMINATION',
 2, 3,
 12,
 DATE '1900-01-01',
 DATE '2013-05-31',
 'SYSTEM');

------------------------------------------------------------

-- 2. Termination After June 2013 > 12 months (Simultaneous)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, EFFECTIVE_FROM, CREATED_BY)
VALUES
('TERM_AFTER_2013_GT_12_SIM',
 'Termination After June 2013 More Than 1 Year - Simultaneous',
 'TERMINATION',
 2, 3,
 12,
 DATE '2013-06-01',
 'SYSTEM');

------------------------------------------------------------

-- 3. Termination After June 2013 > 12 months (Tier 2)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, EFFECTIVE_FROM, CREATED_BY)
VALUES
('TERM_AFTER_2013_GT_12_TIER2',
 'Termination After June 2013 More Than 1 Year - Tier 2',
 'TERMINATION',
 3, 1,
 12,
 DATE '2013-06-01',
 'SYSTEM');

------------------------------------------------------------

-- 4. Termination < 12 months (Tier 2)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('TERM_LT_12_TIER2',
 'Termination Less Than 1 Year - Tier 2',
 'TERMINATION',
 3, 1,
 0, 11,
 'SYSTEM');

------------------------------------------------------------

-- 5. Normal > 12 months (Simultaneous)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('NORMAL_GT_12_SIM',
 'Normal Circumstances More Than 1 Year - Simultaneous',
 'NORMAL',
 2, 3,
 12,
 'SYSTEM');

------------------------------------------------------------

-- 6. Normal < 12 months (Tier 2)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_ELIGIBILITY_MASTER
(RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CESSATION_TYPE_ID, SCHEME_TYPE_ID,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('NORMAL_LT_12_TIER2',
 'Normal Circumstances Less Than 1 Year - Tier 2',
 'NORMAL',
 2, 1,
 0, 11,
 'SYSTEM');



 INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_BEFORE_2019_LT_120', 'CIVIL', DATE '1900-01-01', DATE '2019-06-30', 'LUMPSUM',
 120, NULL, 'LT', 'LUMPSUM',
 'Before July 1 2019, Civil member with less than 120 months is eligible for lumpsum', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_BEFORE_2019_GTE_120', 'CIVIL', DATE '1900-01-01', DATE '2019-06-30', 'OPTION',
 120, NULL, 'GTE', 'PENSION_OR_LUMPSUM_OPTION',
 'Before July 1 2019, Civil member with 120 months or more gets pension or lumpsum option', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_2019_2024_LT_240', 'CIVIL', DATE '2019-07-01', DATE '2024-10-31', 'LUMPSUM',
 240, NULL, 'LT', 'LUMPSUM',
 'From July 1 2019 to October 31 2024, Civil member with less than 240 months is eligible for lumpsum', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_2019_2024_GTE_240', 'CIVIL', DATE '2019-07-01', DATE '2024-10-31', 'OPTION',
 240, NULL, 'GTE', 'PENSION_OR_LUMPSUM_OPTION',
 'From July 1 2019 to October 31 2024, Civil member with 240 months or more gets pension or lumpsum option', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_AFTER_2024_LT_276', 'CIVIL', DATE '2024-11-01', NULL, 'LUMPSUM',
 276, NULL, 'LT', 'LUMPSUM',
 'On and after November 1 2024, Civil member with less than 276 months is eligible for lumpsum, except members who had already attained 240 months before November 1 2024', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('CIVIL_AFTER_2024_GTE_276', 'CIVIL', DATE '2024-11-01', NULL, 'OPTION',
 276, NULL, 'GTE', 'PENSION_OR_LUMPSUM_OPTION',
 'On and after November 1 2024, Civil member with 276 months or more gets pension or lumpsum option', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('AF_BEFORE_2022_LT_120', 'AF', DATE '1900-01-01', DATE '2022-11-30', 'LUMPSUM',
 120, NULL, 'LT', 'LUMPSUM',
 'Before December 1 2022, Armed Force member with less than 120 months is eligible for lumpsum', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('AF_BEFORE_2022_GTE_120', 'AF', DATE '1900-01-01', DATE '2022-11-30', 'OPTION',
 120, NULL, 'GTE', 'PENSION_OR_LUMPSUM_OPTION',
 'Before December 1 2022, Armed Force member with 120 months or more gets pension or lumpsum option', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('AF_AFTER_2022_LT_240', 'AF', DATE '2022-12-02', NULL, 'LUMPSUM',
 240, NULL, 'LT', 'LUMPSUM',
 'On and after December 2 2022, Armed Force member with less than 240 months is eligible for lumpsum', 'Y');

INSERT INTO CLAIM_VESTING_RULE_MASTER
(RULE_CODE, MEMBER_CATEGORY, EFFECTIVE_FROM, EFFECTIVE_TO, REFUND_TYPE,
 MIN_VESTING_MONTHS, MAX_VESTING_MONTHS, COMPARISON_TYPE, PAYOUT_RESULT, REMARKS, IS_ACTIVE)
VALUES
('AF_AFTER_2022_GTE_240', 'AF', DATE '2022-12-02', NULL, 'OPTION',
 240, NULL, 'GTE', 'PENSION_OR_LUMPSUM_OPTION',
 'On and after December 2 2022, Armed Force member with 240 months or more gets pension or lumpsum option', 'Y');





 INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'CIVIL_AF', 'TERMINATION', 'SIMULTANEOUS',
 12, NULL,
 DATE '1900-01-01', DATE '2013-05-31',
 'PF_EC + PF_IEC + PC_MC + PC_IMC + PC_EC + PC_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'CIVIL_AF', 'TERMINATION', 'SIMULTANEOUS',
 12, NULL,
 DATE '2013-06-01', NULL,
 'PF_EC + PF_IEC + PC_EC + PC_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'CIVIL_AF', 'TERMINATION', 'TIER_2',
 12, NULL,
 DATE '2013-06-01', NULL,
 'PF_EC + PF_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'CIVIL_AF', 'TERMINATION', 'TIER_2',
 0, 11,
 DATE '1900-01-01', NULL,
 'PF_EC + PF_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'CIVIL_AF', 'TERMINATION', 'SIMULTANEOUS',
 0, 11,
 DATE '1900-01-01', NULL,
 'PC_EC + PC_IEC + PF_EC + PF_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('NORMAL', 'CIVIL_AF', 'NORMAL', 'TIER_2',
 0, 11,
 DATE '1900-01-01', NULL,
 'PF_EC + PF_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('NORMAL', 'CIVIL_AF', 'NORMAL', 'SIMULTANEOUS',
 0, 11,
 DATE '1900-01-01', NULL,
 'PC_MC + PC_IMC + PC_EC + PC_IEC + PF_EC + PF_IEC',
 'Y');

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER
(CLAIM_CATEGORY_CODE, MEMBER_TYPE, CESSATION_TYPE, SCHEME_TYPE,
 MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
 EFFECTIVE_FROM, EFFECTIVE_TO, LAPSED_FORMULA, IS_ACTIVE)
VALUES
('TERMINATION', 'PRIVATE', 'TERMINATION', 'TIER_2',
 0, 11,
 DATE '1900-01-01', NULL,
 'GOVERNMENT_CONTRIBUTION_IF_ANY_FORFEITED',
 'Y');




 -- PRIVATE - 50% (>= 60 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('04', 50.00, 'N', 'Y', 60, 'SYSTEM');

-- PRIVATE - 75% (>= 180 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('04', 75.00, 'N', 'Y', 180, 'SYSTEM');


-- CIVIL - 50% (>= 60 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('01', 50.00, 'N', 'Y', 60, 'SYSTEM');

-- CIVIL - 75% (>= 180 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('01', 75.00, 'N', 'Y', 180, 'SYSTEM');


-- ARMED_FORCE - 50% (>= 60 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('03', 50.00, 'N', 'Y', 60, 'SYSTEM');

-- ARMED_FORCE - 75% (>= 180 months)
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.PARTIAL_WITHDRAWAL_RULE_MASTER
(CATEGORY_ID, MAX_WITHDRAWAL_PERCENTAGE, PF_ACCUMULATION, TOTAL_ACCUMULATION_VALUE, NUMBER_OF_CONTRIBUTION_MONTHS, CREATED_BY)
VALUES
('03', 75.00, 'N', 'Y', 180, 'SYSTEM');


------------------------------------------------------------
-- CLAIM_LAPSED_REFUND_MASTER
-- Document-derived Civil / AF lapsed refund rules
------------------------------------------------------------

-- 1) Termination (Before June 2013) > 1 year - Simultaneous - Civil/AF
-- Lapsed Fund: PF_EC + PF_IEC and PC_MC + PC_IMC and PC_EC + PC_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_TERM_BEFORE_2013_GT_12_SIM' AS RULE_CODE,
        'Lapsed Fund - Termination Before June 2013 More Than 1 Year - Simultaneous' AS RULE_NAME,
        'TERMINATION' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        ct.ID AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        12 AS MIN_CONTRIBUTION_MONTHS,
        CAST(NULL AS NUMBER) AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        DATE '2013-05-31' AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF termination before June 2013 > 1 year' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CESSATION_TYPE_MASTER ct
      ON ct.CODE = 'TERMINATION'
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'SIMULTANEOUS'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'FULL'
    WHERE cc.CODE = 'TERMINATION'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 2) Termination (After June 2013) > 1 year - Simultaneous - Civil/AF
-- Lapsed Fund: PF_EC + PF_IEC and PC_EC + PC_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_TERM_AFTER_2013_GT_12_SIM' AS RULE_CODE,
        'Lapsed Fund - Termination After June 2013 More Than 1 Year - Simultaneous' AS RULE_NAME,
        'TERMINATION' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        ct.ID AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        12 AS MIN_CONTRIBUTION_MONTHS,
        CAST(NULL AS NUMBER) AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '2013-06-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF termination after June 2013 > 1 year simultaneous' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CESSATION_TYPE_MASTER ct
      ON ct.CODE = 'TERMINATION'
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'SIMULTANEOUS'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'FULL'
    WHERE cc.CODE = 'TERMINATION'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 3) Termination (After June 2013) > 1 year - Tier 2 - Civil/AF
-- Lapsed Fund: PF_EC + PF_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_TERM_AFTER_2013_GT_12_TIER2' AS RULE_CODE,
        'Lapsed Fund - Termination After June 2013 More Than 1 Year - Tier 2' AS RULE_NAME,
        'TERMINATION' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        ct.ID AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        12 AS MIN_CONTRIBUTION_MONTHS,
        CAST(NULL AS NUMBER) AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '2013-06-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF termination after June 2013 > 1 year tier 2' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CESSATION_TYPE_MASTER ct
      ON ct.CODE = 'TERMINATION'
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'TIER_2'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'PF'
    WHERE cc.CODE = 'TERMINATION'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 4) Termination < 1 year - Tier 2 - Civil/AF
-- Lapsed Fund: PF_EC + PF_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_TERM_LT_12_TIER2' AS RULE_CODE,
        'Lapsed Fund - Termination Less Than 1 Year - Tier 2' AS RULE_NAME,
        'TERMINATION' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        ct.ID AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        0 AS MIN_CONTRIBUTION_MONTHS,
        11 AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF termination less than 1 year tier 2' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CESSATION_TYPE_MASTER ct
      ON ct.CODE = 'TERMINATION'
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'TIER_2'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'PF'
    WHERE cc.CODE = 'TERMINATION'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 5) Termination < 1 year - Simultaneous - Civil/AF
-- Lapsed Fund: PC_EC + PC_IEC and PF_EC + PF_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_TERM_LT_12_SIM' AS RULE_CODE,
        'Lapsed Fund - Termination Less Than 1 Year - Simultaneous' AS RULE_NAME,
        'TERMINATION' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        ct.ID AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        0 AS MIN_CONTRIBUTION_MONTHS,
        11 AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF termination less than 1 year simultaneous' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CESSATION_TYPE_MASTER ct
      ON ct.CODE = 'TERMINATION'
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'SIMULTANEOUS'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'FULL'
    WHERE cc.CODE = 'TERMINATION'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 6) Normal < 1 year - Tier 2 - Civil/AF
-- Lapsed Fund: PF_EC + PF_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_NORMAL_LT_12_TIER2' AS RULE_CODE,
        'Lapsed Fund - Normal Less Than 1 Year - Tier 2' AS RULE_NAME,
        'NORMAL' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        CAST(NULL AS NUMBER) AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        0 AS MIN_CONTRIBUTION_MONTHS,
        11 AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF normal less than 1 year tier 2' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'TIER_2'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'PF'
    WHERE cc.CODE = 'NORMAL'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

-- 7) Normal < 1 year - Simultaneous - Civil/AF
-- Lapsed Fund: PC_MC + PC_IMC and PC_EC + PC_IEC and PF_EC + PF_IEC
MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_NORMAL_LT_12_SIM' AS RULE_CODE,
        'Lapsed Fund - Normal Less Than 1 Year - Simultaneous' AS RULE_NAME,
        'NORMAL' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        CAST(NULL AS NUMBER) AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        0 AS MIN_CONTRIBUTION_MONTHS,
        11 AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Derived from Claim Eligibility table - Civil/AF normal less than 1 year simultaneous' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'SIMULTANEOUS'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'FULL'
    WHERE cc.CODE = 'NORMAL'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE, RULE_NAME, CLAIM_CATEGORY_CODE, CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID, SCHEME_TYPE_ID, MIN_CONTRIBUTION_MONTHS, MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID, EFFECTIVE_FROM, EFFECTIVE_TO, REMARKS, CREATED_BY
)
VALUES (
    src.RULE_CODE, src.RULE_NAME, src.CLAIM_CATEGORY_CODE, src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID, src.SCHEME_TYPE_ID, src.MIN_CONTRIBUTION_MONTHS, src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID, src.EFFECTIVE_FROM, src.EFFECTIVE_TO, src.REMARKS, 'SYSTEM'
);

------------------------------------------------------------
-- CLAIM_LAPSED_REFUND_CATEGORY_MAP
-- Civil = 01, Armed Forces = 03
------------------------------------------------------------

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_CATEGORY_MAP (RULE_ID, CATEGORY_ID)
SELECT r.ID, c.CATEGORY_ID
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_MASTER_SERVICE_SCHEMA.AGENCY_CATEGORIES c
  ON c.CATEGORY_ID IN ('01','03')
WHERE r.RULE_CODE IN (
    'LAPSE_TERM_BEFORE_2013_GT_12_SIM',
    'LAPSE_TERM_AFTER_2013_GT_12_SIM',
    'LAPSE_TERM_AFTER_2013_GT_12_TIER2',
    'LAPSE_TERM_LT_12_TIER2',
    'LAPSE_TERM_LT_12_SIM',
    'LAPSE_NORMAL_LT_12_TIER2',
    'LAPSE_NORMAL_LT_12_SIM'
)
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_CATEGORY_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.CATEGORY_ID = c.CATEGORY_ID
);

------------------------------------------------------------
-- CLAIM_LAPSED_REFUND_COMPONENT_MAP
------------------------------------------------------------

-- Rule 1: Before 2013 > 1 year SIM -> PF_EMPLOYER_WITH_INTEREST + PENSION_MEMBER_WITH_INTEREST + PENSION_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE IN ('PF_EMPLOYER_WITH_INTEREST', 'PENSION_MEMBER_WITH_INTEREST', 'PENSION_EMPLOYER_WITH_INTEREST')
WHERE r.RULE_CODE = 'LAPSE_TERM_BEFORE_2013_GT_12_SIM'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 2: After 2013 > 1 year SIM -> PF_EMPLOYER_WITH_INTEREST + PENSION_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE IN ('PF_EMPLOYER_WITH_INTEREST', 'PENSION_EMPLOYER_WITH_INTEREST')
WHERE r.RULE_CODE = 'LAPSE_TERM_AFTER_2013_GT_12_SIM'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 3: After 2013 > 1 year TIER2 -> PF_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE = 'PF_EMPLOYER_WITH_INTEREST'
WHERE r.RULE_CODE = 'LAPSE_TERM_AFTER_2013_GT_12_TIER2'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 4: Termination < 1 year TIER2 -> PF_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE = 'PF_EMPLOYER_WITH_INTEREST'
WHERE r.RULE_CODE = 'LAPSE_TERM_LT_12_TIER2'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 5: Termination < 1 year SIM -> PF_EMPLOYER_WITH_INTEREST + PENSION_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE IN ('PF_EMPLOYER_WITH_INTEREST', 'PENSION_EMPLOYER_WITH_INTEREST')
WHERE r.RULE_CODE = 'LAPSE_TERM_LT_12_SIM'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 6: Normal < 1 year TIER2 -> PF_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE = 'PF_EMPLOYER_WITH_INTEREST'
WHERE r.RULE_CODE = 'LAPSE_NORMAL_LT_12_TIER2'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

-- Rule 7: Normal < 1 year SIM -> PENSION_MEMBER_WITH_INTEREST + PENSION_EMPLOYER_WITH_INTEREST + PF_EMPLOYER_WITH_INTEREST
INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE IN ('PENSION_MEMBER_WITH_INTEREST', 'PENSION_EMPLOYER_WITH_INTEREST', 'PF_EMPLOYER_WITH_INTEREST')
WHERE r.RULE_CODE = 'LAPSE_NORMAL_LT_12_SIM'
AND NOT EXISTS (
    SELECT 1
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
    WHERE m.RULE_ID = r.ID
      AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
);

COMMIT;


------------------------------------------------------------
-- PRIVATE Lapsed Refund Rule
-- Source:
-- Private PF members are PF only.
-- Less than 5 years -> member gets own contribution + interest,
-- employer contribution + interest goes to lapsed fund or refunded to agency.
------------------------------------------------------------

MERGE INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER t
USING (
    SELECT
        'LAPSE_PRIVATE_LT_60_TIER2' AS RULE_CODE,
        'Lapsed Fund - Private Less Than 5 Years - Tier 2' AS RULE_NAME,
        'NORMAL' AS CLAIM_CATEGORY_CODE,
        cc.ID AS CLAIM_CIRCUMSTANCE_ID,
        CAST(NULL AS NUMBER) AS CESSATION_TYPE_ID,
        sm.ID AS SCHEME_TYPE_ID,
        0 AS MIN_CONTRIBUTION_MONTHS,
        59 AS MAX_CONTRIBUTION_MONTHS,
        bt.ID AS BENEFIT_TYPE_ID,
        DATE '1900-01-01' AS EFFECTIVE_FROM,
        CAST(NULL AS DATE) AS EFFECTIVE_TO,
        'Private PF < 5 years: employer contribution with interest to lapsed fund or refundable to agency as configured' AS REMARKS
    FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_CIRCUMSTANCE_MASTER cc
    JOIN PPFMS_CONTRIBUTIONS_PAYMENTS_SERVICE_SCHEMA.SCHEME_MASTER sm
      ON sm.CODE = 'TIER_2'
    LEFT JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_TYPE_MASTER bt
      ON bt.CODE = 'PF'
    WHERE cc.CODE = 'NORMAL'
) src
ON (t.RULE_CODE = src.RULE_CODE)
WHEN NOT MATCHED THEN
INSERT (
    RULE_CODE,
    RULE_NAME,
    CLAIM_CATEGORY_CODE,
    CLAIM_CIRCUMSTANCE_ID,
    CESSATION_TYPE_ID,
    SCHEME_TYPE_ID,
    MIN_CONTRIBUTION_MONTHS,
    MAX_CONTRIBUTION_MONTHS,
    BENEFIT_TYPE_ID,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    REMARKS,
    CREATED_BY
)
VALUES (
    src.RULE_CODE,
    src.RULE_NAME,
    src.CLAIM_CATEGORY_CODE,
    src.CLAIM_CIRCUMSTANCE_ID,
    src.CESSATION_TYPE_ID,
    src.SCHEME_TYPE_ID,
    src.MIN_CONTRIBUTION_MONTHS,
    src.MAX_CONTRIBUTION_MONTHS,
    src.BENEFIT_TYPE_ID,
    src.EFFECTIVE_FROM,
    src.EFFECTIVE_TO,
    src.REMARKS,
    'SYSTEM'
);

------------------------------------------------------------
-- CATEGORY MAP
-- PRIVATE = 04
------------------------------------------------------------

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_CATEGORY_MAP
(RULE_ID, CATEGORY_ID)
SELECT r.ID, '04'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
WHERE r.RULE_CODE = 'LAPSE_PRIVATE_LT_60_TIER2'
  AND NOT EXISTS (
      SELECT 1
      FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_CATEGORY_MAP m
      WHERE m.RULE_ID = r.ID
        AND m.CATEGORY_ID = '04'
  );

------------------------------------------------------------
-- COMPONENT MAP
-- Private < 5 years -> employer contribution + interest goes to lapsed fund
------------------------------------------------------------

INSERT INTO PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP
(RULE_ID, BENEFIT_COMPONENT_TYPE_ID, CREATED_BY)
SELECT r.ID, b.ID, 'SYSTEM'
FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_MASTER r
JOIN PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.BENEFIT_COMPONENT_TYPE_MASTER b
  ON b.CODE = 'PF_EMPLOYER_WITH_INTEREST'
WHERE r.RULE_CODE = 'LAPSE_PRIVATE_LT_60_TIER2'
  AND NOT EXISTS (
      SELECT 1
      FROM PPFMS_CLAIMS_WORKFLOW_SERVICE_SCHEMA.CLAIM_LAPSED_REFUND_COMPONENT_MAP m
      WHERE m.RULE_ID = r.ID
        AND m.BENEFIT_COMPONENT_TYPE_ID = b.ID
  );

COMMIT;