server:
  port: 8085

spring:
  application:
    name: claim-processing

  datasource:
    url: jdbc:oracle:thin:@//10.15.15.20:1521/NPPFDB
    username: premia_nppf
    password: PremiaNPPF2025
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jackson:
    time-zone: Asia/Thimphu

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          time_zone: Asia/Thimphu

  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  session:
    store-type: redis

  data:
    redis:
      host: 10.15.15.20
      port: 6379
      password: Ruf0us@324#
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
        shutdown-timeout: 2000ms

app:
  resources:
    images:
      path: /images
    videos:
      path: /videos

logging:
  file:
    name: logs/application.log
  level:
    nppf.org.bt.claim-processing: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    redis:
      enabled: true
    session:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true